version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todouser
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
